#pragma once 
#include <cstdint>
#include <Chip/Unknown/STMicro/STM32F7x/RNG.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/HASH.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/CRYP.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/DCMI.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/FMC.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/DBG.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/DMA2.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/DMA1.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/RCC.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/GPIOD.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/GPIOC.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/GPIOK.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/GPIOJ.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/GPIOI.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/GPIOH.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/GPIOG.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/GPIOF.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/GPIOE.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/GPIOB.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/GPIOA.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/SYSCFG.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/SPI1.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/SPI2.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/SPI3.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/SPI4.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/SPI5.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/SPI6.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/ADC1.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/ADC2.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/ADC3.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/DAC.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/PWR.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/IWDG.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/WWDG.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/C_ADC.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/TIM1.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/TIM8.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/TIM2.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/TIM3.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/TIM4.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/TIM5.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/TIM9.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/TIM12.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/TIM10.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/TIM11.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/TIM13.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/TIM14.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/TIM6.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/TIM7.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/Ethernet_MAC.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/Ethernet_MMC.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/Ethernet_PTP.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/Ethernet_DMA.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/CRC.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/CAN1.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/CAN2.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/NVIC.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/FLASH.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/EXTI.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/LTDC.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/SAI1.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/SAI2.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/DMA2D.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/QUADSPI.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/CEC.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/SPDIF_RX.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/SDMMC1.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/LPTIM1.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/I2C1.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/I2C2.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/I2C3.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/I2C4.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/RTC.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/USART6.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/USART1.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/USART3.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/USART2.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/UART5.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/UART4.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/UART8.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/UART7.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/OTG_FS_GLOBAL.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/OTG_FS_HOST.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/OTG_FS_DEVICE.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/OTG_FS_PWRCLK.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/OTG_HS_GLOBAL.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/OTG_HS_HOST.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/OTG_HS_DEVICE.hpp>
#include <Chip/Unknown/STMicro/STM32F7x/OTG_HS_PWRCLK.hpp>
